In [30]:
import numpy as np
x = 10
tablero_numeros = np.arange(100)
tablero_numeros = np.reshape(tablero_numeros, (x,x))
print(tablero)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


# PROGRAMA

#### Importar

In [14]:
from utils import *
import variables as vr

### Crear tableros vacíos

In [15]:
#Tablero 1 Jugador (barcos Jug con disparos Rival)
tablero_barcos_jugador = crear_tablero()

#Tablero 2 Jugador (disparos Jug)
tablero_disparos_jugador = crear_tablero()

#Tablero 1 Rival (barcos Rival con disparos Jug)
tablero_barcos_rival = crear_tablero()

#Tablero 2 Rival (disparos Rival)
tablero_disparos_rival = crear_tablero()

In [16]:
print(tablero_barcos_jugador)
print(tablero_disparos_jugador)
print(tablero_barcos_rival)
print(tablero_disparos_rival)

[['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']]
[['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']]
[['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_'

#### Colocar barcos


In [41]:
tablero_barcos_jugador = crear_tablero()
barcos_eslora = ((3,2),(2,3),(1,4)) # (nº de barcos, longitud del barco)

todos_los_barcos = []

for num_barcos, eslora in barcos_eslora:
    for _ in range(num_barcos):
        barco = colocar_barco(eslora)
        todos_los_barcos.append(barco)

for barco in todos_los_barcos:
    tablero_barcos_jugador = dibujar_barco(barco, tablero_barcos_jugador)
print(tablero_barcos_jugador)

[['O' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['O' 'O' '_' '_' '_' '_' 'O' 'O' 'O' '_']
 ['O' 'O' '_' '_' '_' '_' '_' '_' 'O' '_']
 ['_' 'O' '_' 'O' 'O' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' 'O' 'O' 'O' 'O' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']]
