In [5]:
import numpy as np

In [6]:
tablero = np.full((10,10), "_")
print(tablero)

[['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']]


In [7]:
###### barcos colocados manualmente #####

# reseteamos el tablero
tablero = np.full((10,10), "_")

# ponemos sólo el extremo de cada barco
tablero[0,3] = "O"
tablero[0,4] = "O"
tablero[0,5] = "O"
tablero[0,6] = "O"
print(tablero)

[['_' '_' '_' 'O' 'O' 'O' 'O' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']]


In [8]:
###### barcos colocados manualmente #####

# reseteamos el tablero
tablero = np.full((10,10), "_")

# colocamos los barcos desde lista
barco = [[0,3], [0,4], [0,5], [0,6]]

for i in barco:
    tablero[i[0],i[1]]= "O"

print(tablero)

[['_' '_' '_' 'O' 'O' 'O' 'O' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']]


In [9]:
#### definimos una función para colocar los barcos automáticamente

def colocar_barco(barco):
    # colocamos los barcos desde lista
    barco = [[0,3], [0,4], [0,5], [0,6]]

    for i in barco:
        tablero[i[0],i[1]]= "O"

    print(tablero)

In [10]:
##### definimos los barcos
barco_1 = [[0,3], [0,4], [0,5], [0,6]]
barco_2 = [[4,7], [5,7], [6,7]]

colocar_barco(barco_1)
colocar_barco(barco_2)

[['_' '_' '_' 'O' 'O' 'O' 'O' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']]
[['_' '_' '_' 'O' 'O' 'O' 'O' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']]


In [11]:


barco_jugador = [[[0,3], [0,4], [0,5], [0,6]], [[4,7], [5,7], [6,7]], [[8,8], [8,9]], [[1,7]]]

for i in barco_jugador:
    for j in i:
        tablero[j[0], j[1]] = 'O'

print(tablero)


[['_' '_' '_' 'O' 'O' 'O' 'O' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' 'O' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' 'O' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' 'O' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' 'O' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_' '_' '_' '_' 'O' 'O']
 ['_' '_' '_' '_' '_' '_' '_' '_' '_' '_']]


In [12]:
import utils
import variables as vr

tablero_jugador = utils.crear_tablero()

tablero_modificado = utils.colocar_barco(vr.barco_jugador, tablero_jugador)
#print(tablero_jugador)

# disparar
def disparar(casilla,tablero):
    if tablero[casilla] in ('O', 'X'):
        tablero[casilla] = "X"
    elif tablero[casilla] in ("_", 'A'):
        tablero[casilla] = "A"
    return tablero

print(disparar((1,3), tablero_en_curso))


TypeError: colocar_barco() takes 1 positional argument but 2 were given

In [ ]:
#def crear_barco(eslora):
#   barco = np.arange(eslora)
import numpy as np

# casilla inicial aleatoria
eslora = 3
casilla_inicial = [np.random.randint(0, 10, 2)]
print(type(casilla_inicial), casilla_inicial)
# p.ej. [0 8]

# extiendo a derecha
barco = np.append([],casilla_inicial)
#barco = [[0,8],[0,9]]
print(barco)

In [ ]:
# función que calcula si la casilla inicial es válida para un barco de una longitud y una dirección (vertical/horiz.) dadas
def validar_casilla_inicial(casilla, eslora, es_vertical, tablero = 10):
    if (0 <= casilla[0] <= (tablero - 1)) and (0 <= casilla[1] <= (tablero - 1)):
        if es_vertical:
            if (casilla[0] + eslora - 1) < tablero:
                casilla_valida = True
            else:
                casilla_valida = False
        else:
            if (casilla[1] + eslora - 1) < tablero:
                casilla_valida = True
            else:
                casilla_valida = False
    else:
        print("¡La casilla inicial debe estar dentro del Tablero!")
        casilla_valida = False
    return casilla_valida

print("Casilla inicial válida:", validar_casilla_inicial((3,2), 2, False, 6))

Casilla inicial válida: True


In [ ]:
# crear barcos
def crear_barco(eslora):
    barco = np.full(eslora, "O")
    return (barco)

barco_1 = crear_barco(2)
barco_2 = crear_barco(2)
barco_3 = crear_barco(2)
barco_4 = crear_barco(3)
barco_5 = crear_barco(3)
barco_6 = crear_barco(4)

barco_1

array(['O', 'O'], dtype='<U1')

In [ ]:

def colocar_barco (barco):
    eslora = len(barco)
    casilla_valida = False
    coordenadas = []

    # obtengo una casilla inicial y una dirección válidas para la longitud del barco
    while not casilla_valida:
        casilla_inicial = np.random.randint(0, tamano_tablero, 2) # casilla inicial aleatoria
        direccion = np.random.randint(0,2) # obtengo una dirección (horizontal o vertical) aleatoriamente
        # 0: horizontal, 1: vertical
        casilla_valida = validar_casilla_inicial(casilla_inicial, eslora, direccion)
    #print("casilla inicial:", casilla_inicial, "vertical?", direccion, "eslora", eslora)

    # convierto la casilla inicial en la primera casilla del barco a colocar
    coordenadas.append(casilla_inicial.tolist())
    
    # calculo la localización del barco en el tablero
    fila_sgte = coordenadas[0][0]
    columna_sgte = coordenadas[0][1]
    #print("antes del for:", coordenadas,"fila y columna:", fila_sgte, columna_sgte)

    for i in range(1, eslora): #desde 1 hasta eslora-1
        if direccion: #direccion = 1, es vertical
            fila_sgte = fila_sgte + 1 # Vertical, Aumentamos la fila
        else: # direccion = 0, es horizontal
            columna_sgte = columna_sgte + 1 # Horizontal, Aumentamos la columna
        celda_siguiente = [fila_sgte, columna_sgte]
        coordenadas.append(celda_siguiente)

    #print("después del for:", coordenadas)

    barco_colocado = np.array(coordenadas) # convierto la lista en un array de numpy
    return barco_colocado

In [ ]:
print(colocar_barco(barco_6))

[[5 6]
 [6 6]
 [7 6]
 [8 6]]


In [ ]:
import numpy as np
x = 10
tablero = np.arange(100)
tablero = np.reshape(tablero, (x,x))
print(tablero)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
import utils
import variables as vr

In [ ]:
barco_1 = crear_barco(2)
barco_2 = crear_barco(2)
barco_3 = crear_barco(2)
barco_4 = crear_barco(3)
barco_5 = crear_barco(3)
barco_6 = crear_barco(4)

NameError: name 'crear_barco' is not defined

In [ ]:
tablero_jugador = utils.crear_tablero()
tablero_rival = utils.crear_tablero()
print("-"*10)

tablero_modificado = utils.dibujar_barco(vr.barco_1, tablero_jugador)
print(tablero_jugador)

print("-"*10)

utils.disparar((0,2), tablero_modificado)
print(tablero_jugador)

utils.validar_casilla_inicial()

----------


AttributeError: module 'utils' has no attribute 'dibujar_barco'