![imagen](./img/ejercicios.png)

In [2]:
import numpy as np
np.__version__

'2.2.5'

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [6]:
my_array = np.arange(0,10)
print(my_array)

print(my_array[-1: 0: -2])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [8]:
print(my_array[-2: -4: -1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [10]:
print(my_array[2:: -1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [ ]:
# 1. Crea una matriz de 4x5, con una secuencia del 1 al 20
matriz_4 = np.arange(1, 21)
matriz_4 = matriz_4.reshape(4, 5)
print('matriz de 4 x 5:\n', matriz_4)

print("-------------")
# 2. Invierte totalmente la matriz. Tanto las filas, como las columnas
print('matriz de 4 x 5 invertida:\n', matriz_4[::-1, ::-1])

matriz de 4 x 5:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
-------------
matriz de 4 x 5 invertida:
 [[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [25]:
print('matriz original\n', matriz_4)
matriz_5 = matriz_4[:2, :2]
print('matriz modificada\n', matriz_5)

matriz original
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
matriz modificada
 [[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [27]:
print('matriz original\n', matriz_4)
matriz_6 = matriz_4[::2, ::2]
print('matriz modificada\n', matriz_6)

matriz original
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
matriz modificada
 [[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [38]:
print('matriz original\n', matriz_4)
matriz_5 = matriz_4[:3:, ::-1]
print('matriz modificada\n', matriz_5)

matriz original
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
matriz modificada
 [[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [48]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

print("Método 1: con una máscara que permita filtrar sólo los loros")
mascara = np.array(x == "Loro")
solo_loros_1 = x[mascara]
print(solo_loros_1)

print("-----------")

print("Método 2: filtrando directamente en una línea")
solo_loros_2 = x[x == "Loro"]
print(solo_loros_2)

Método 1: con una máscara que permita filtrar sólo los loros
['Loro' 'Loro']
-----------
Método 2: filtrando directamente en una línea
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [53]:
# Crea una secuencia de 20 elementos
matriz_9 = np.arange(20)
print('matriz de 20 elementos:\n', matriz_9)

matriz_9 = matriz_9.reshape(2, 5, 2)
print('array de 2 matrices de 5x2:\n', matriz_9)

matriz de 20 elementos:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
array de 2 matrices de 5x2:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [61]:
x = np.zeros(10, dtype=int)
print("Array inicial:", x)
print("Ocupa", x.nbytes, "bytes en memoria.")

x[3]= 1
print("\nArray modificado:", x)
print("Sigue ocupando", x.nbytes, "bytes en memoria.")

Array inicial: [0 0 0 0 0 0 0 0 0 0]
Ocupa 80 bytes en memoria.

Array modificado: [0 0 0 1 0 0 0 0 0 0]
Sigue ocupando 80 bytes en memoria.


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [65]:
vector = np.arange(10, 50)
print("Vector original:\n", vector)

vector_invertido = vector[::-1]
print("Vector invertido:\n", vector_invertido)


Vector original:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Vector invertido:
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [71]:
def indices(vector):
    return np.nonzero(vector)[0]

In [73]:
vector_12 = np.array([1,2,0,0,4,0])
print(indices(vector_12))

[0 1 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [94]:
# Crea una matriz de números aleatorios 10x10
matriz_13 = np.random.rand(10, 10)
print("Matriz:\n", matriz_13)

# Encuentra los valores mínimo y máximo
minimo = np.min(matriz_13)
maximo = np.max(matriz_13)

print("\nValor mínimo:", minimo)
print("Valor máximo:", maximo)


Matriz:
 [[6.41775967e-01 6.99814117e-01 2.64021389e-01 5.84830847e-02
  2.62255416e-01 2.07866454e-01 7.97636980e-01 2.69300698e-01
  2.27767616e-01 9.04838725e-01]
 [7.82601047e-01 1.91738578e-01 8.03802305e-01 8.47054457e-01
  3.54044934e-01 3.15875599e-01 2.00063271e-01 5.88005923e-01
  4.92777011e-01 8.55431009e-01]
 [8.04966838e-01 9.39982124e-01 7.19287530e-01 7.23015922e-01
  3.20109096e-02 5.55349249e-01 3.89095007e-01 7.89503416e-02
  5.01150431e-01 3.86369674e-01]
 [4.61813075e-01 5.65570163e-01 2.70986233e-01 7.09946935e-01
  3.87252710e-01 2.97706193e-01 6.56933831e-01 5.48654378e-01
  4.09321577e-01 1.19931178e-02]
 [7.76606857e-01 7.46526453e-01 1.95239007e-01 8.69352072e-01
  2.90795149e-01 3.43342093e-01 2.74344591e-01 8.01737656e-01
  5.77779566e-01 9.56465107e-01]
 [9.86652745e-01 4.12918097e-01 7.23219224e-01 7.60847941e-01
  8.43824274e-01 2.51231353e-02 3.08657667e-01 2.47446588e-01
  4.87757624e-02 6.70100431e-02]
 [6.90613907e-01 4.26900437e-01 8.72052573e-01 1.

## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [74]:
vector_aleatorio = np.random.rand(30)
print("Vector aleatorio:", vector_aleatorio)

media = np.mean(vector_aleatorio)
print("Media del vector:", media)



Vector aleatorio: [0.21839617 0.08604605 0.43885073 0.25012022 0.2495894  0.8335099
 0.4390999  0.97156815 0.49883795 0.01268824 0.14121408 0.92633284
 0.39165428 0.86415193 0.66187743 0.01091753 0.64448101 0.94729239
 0.49532163 0.20979789 0.35292712 0.79568344 0.32433876 0.00650007
 0.90657297 0.43257513 0.09977642 0.0281117  0.97494263 0.23535717]
Media del vector: 0.448284437614845


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [87]:
cuadrado = np.zeros((5, 5), dtype=int)

# primera fila
cuadrado[0, :] = 1

# última fila
cuadrado[-1, :] = 1

# primera columna
cuadrado[:, 0] = 1

# última columna
cuadrado[:, -1] = 1

print(cuadrado)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [86]:
matriz_16 = np.zeros((8, 8), dtype=int)

# ponemos a 1 los 0's alternando en cada columna / fila
matriz_16[1::2, ::2] = 1
matriz_16[::2, 1::2] = 1

print(matriz_16)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [85]:
# creamos el patrón a repetir
matriz_17 = np.array([[0, 1],
                   [1, 0]])
matriz_17 = np.tile(matriz_17, (4,4))
print(matriz_17)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [89]:
# Crear matriz aleatoria 5x5
matriz = np.random.rand(5, 5)
print("Matriz original:\n", matriz)

# Calcular media y desviación estándar
media = np.mean(matriz)
estandar = np.std(matriz)

# Normalizar
matriz_normalizada = (matriz - media) / estandar
print("\nMatriz normalizada:\n", matriz_normalizada)


Matriz original:
 [[0.98578598 0.69767626 0.98667558 0.41480538 0.53241181]
 [0.13664493 0.56155452 0.43550103 0.68267965 0.02348519]
 [0.98633784 0.54895021 0.57622906 0.99744342 0.77120551]
 [0.5035747  0.65086404 0.30436797 0.38882144 0.59320929]
 [0.32302778 0.0372207  0.67469001 0.81118412 0.16181825]]

Matriz normalizada:
 [[ 1.53966817  0.5183623   1.54282167 -0.48437262 -0.06747544]
 [-1.47040981  0.03583112 -0.41100965  0.46520156 -1.87154415]
 [ 1.54162441 -0.00884929  0.08785015  1.58099203  0.77901249]
 [-0.16969866  0.35241999 -0.87585672 -0.57648181  0.14804253]
 [-0.8097105  -1.8228538   0.4368795   0.92073068 -1.38117415]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [99]:
#1. Crea una secuencia de números que vayan del 0 al 10.
x = np.arange(0, 11)
print("Array inicial:", x)

# 2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1,
# todos los elementos cuyo valor se encuentre entre el 3 y el 8.
x_copia = x.copy()
x_copia[(x_copia >= 3) & (x_copia <= 8)] = -1
print(x_copia)

Array inicial: [ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
