![imagen](./img/ejercicios.png)

In [3]:
import numpy as np
np.__version__

'2.2.5'

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [5]:
my_array = np.arange(0,10)
print(my_array)

print(my_array[-1: 0: -2])
print(my_array[:: -2])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [6]:
print(my_array[-2: -4: -1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [11]:
print(my_array[2:: -1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [18]:
# 1. Crea una matriz de 4x5, con una secuencia del 1 al 20
matriz_4 = np.arange(1, 21)
matriz_4 = matriz_4.reshape(4, 5)
print('matriz de 4 x 5:\n', matriz_4)

print("-------------")
# 2. Invierte totalmente la matriz. Tanto las filas, como las columnas
print('matriz de 4 x 5 invertida:\n', matriz_4[::-1, ::-1])
print(np.flip(matriz_4))
print(matriz_4.T) #??????????????????????????????? transpose

matriz de 4 x 5:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
-------------
matriz de 4 x 5 invertida:
 [[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [25]:
print('matriz original\n', matriz_4)
matriz_5 = matriz_4[:2, :2]
print('matriz modificada\n', matriz_5)

matriz original
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
matriz modificada
 [[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [27]:
print('matriz original\n', matriz_4)
matriz_6 = matriz_4[::2, ::2]
print('matriz modificada\n', matriz_6)

matriz original
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
matriz modificada
 [[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [20]:
print('matriz original\n', matriz_4)
matriz_7 = matriz_4[:3, ::-1]
print('matriz modificada\n', matriz_7)

matriz original
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
matriz modificada
 [[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [29]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

print("Método 1: con una máscara que permita filtrar sólo los loros")
mascara = np.array(x == "Loro")
solo_loros_1 = x[mascara]
print(solo_loros_1)

print("-----------")

print("Método 2: filtrando directamente en una línea")
solo_loros_2 = x[x == "Loro"]
print(solo_loros_2)

print("-----------")

print("Método 3: utilizando Where")
solo_loros_3 = x[np.where(x == "Loro")]
print(solo_loros_3)

Método 1: con una máscara que permita filtrar sólo los loros
['Loro' 'Loro']
-----------
Método 2: filtrando directamente en una línea
['Loro' 'Loro']
-----------
Método 3: utilizando Where
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [34]:
# Crea una secuencia de 20 elementos
matriz_9 = np.arange(20)
print('matriz de 20 elementos:\n', matriz_9)
print("-----------------")
matriz_9 = matriz_9.reshape(2, 5, 2)
print('array de 2 matrices de 5x2:\n', matriz_9)
print("-----------------")
print("dimensiones:",matriz_9.ndim)
print("forma:",matriz_9.shape)
print("tamaño:",matriz_9.size)

matriz de 20 elementos:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
-----------------
array de 2 matrices de 5x2:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
-----------------
dimensiones: 3
forma: (2, 5, 2)
tamaño: 20


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [55]:
x = np.zeros(10, dtype=int)
print("Array inicial:", x)
print("Ocupa", x.nbytes, "bytes en memoria.")
print("Itemsize:", x.itemsize)

x[3]= 1
print("\nArray modificado:", x)
print("Ocupa", x.nbytes, "bytes en memoria.")
print("Itemsize:", x.itemsize)

print("\n------------------")
y = np.random.rand(10)
print("\nArray de Floats:", y)
print("Ocupa", y.nbytes, "bytes en memoria.")
print("Itemsize:", y.itemsize)

Array inicial: [0 0 0 0 0 0 0 0 0 0]
Ocupa 80 bytes en memoria.
Itemsize: 8

Array modificado: [0 0 0 1 0 0 0 0 0 0]
Ocupa 80 bytes en memoria.
Itemsize: 8

------------------

Array de Floats: [0.81405305 0.74508827 0.21109583 0.32364224 0.22128144 0.9615916
 0.50800365 0.73785814 0.83750666 0.78108518]
Ocupa 80 bytes en memoria.
Itemsize: 8


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [65]:
vector = np.arange(10, 50)
print("Vector original:\n", vector)

vector_invertido = vector[::-1]
print("Vector invertido:\n", vector_invertido)


Vector original:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Vector invertido:
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [71]:
# método 1: con el método nonzero
def indices_nonzero(vector):
    return np.nonzero(vector)[0]

# método 1: con el método where
def indices_where(vector):
    return np.where(vector != 0)[0]

In [74]:
vector_12 = np.array([1,2,0,0,4,0])
print("vector original:", vector_12)
print(indices_where(vector_12))
print(*indices_nonzero(vector_12))

# el asterisco (*) es el operador de desempaquetado.
# Lo que hace es tomar el iterable devuelto por la función y "desempaquetar" sus elementos,
# pasándolos como argumentos individuales a la función print.

vector original: [1 2 0 0 4 0]
[0 1 4]
0 1 4


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [89]:
# Crea una matriz de números aleatorios 10x10
matriz_13 = np.random.randint(100, size =(10, 10))
print("Matriz:\n", matriz_13)

# Encuentra los valores mínimo y máximo
minimo = np.min(matriz_13)
maximo = np.max(matriz_13)

print("\nValor mínimo:", minimo)
print("Valor máximo:", maximo)


Matriz:
 [[83 57 62 65 44  3 72  5 55 92]
 [57 45 27 46 36 50 24 88 72 88]
 [76 53  2 66 55 85 27 54  8 11]
 [38 51 73 32 93 57 80 12 43 98]
 [42 25 53 14 83 11 74 70 43 15]
 [34 50 53 80 11  9 97 66 65 81]
 [55 23 93 58 90 77 44 80 53 21]
 [ 7 72 86 95  2 11 95 23 12 12]
 [33 90 14  2 55 55 21 14 76 45]
 [74 79 42 79 45 87 78 91 57 26]]

Valor mínimo: 2
Valor máximo: 98


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [101]:
vector_aleatorio = np.random.randint(100, size=30)
print("Vector aleatorio:\n", vector_aleatorio)

print("\nValor mínimo:", np.min(vector_aleatorio))
print("Valor máximo:", np.max(vector_aleatorio))

media = np.mean(vector_aleatorio)
print("Media del vector:", media)

print("---------")
vector_aleatorio_2 = np.random.random(30)
print(vector_aleatorio_2 )

print("---------")
vector_aleatorio_3 = np.random.rand(30)
print(vector_aleatorio_3 )


Vector aleatorio:
 [72 55 48 45 49 72 14  9 46 89 42 62 75 84 38 54 80  0 96 46 61 23 45 16
 39  2 76 40 67 37]

Valor mínimo: 0
Valor máximo: 96
Media del vector: 49.4
---------
[0.50317952 0.98152779 0.68481509 0.73036834 0.62203903 0.63564114
 0.51975316 0.32540296 0.26435539 0.69240628 0.24175737 0.39137843
 0.29787165 0.37429519 0.57093019 0.95427803 0.9776985  0.78414912
 0.55148015 0.17106576 0.34938256 0.3747591  0.01516567 0.34076378
 0.13776334 0.98645424 0.19937302 0.72493939 0.42483374 0.16661305]
---------
[0.90717615 0.00153441 0.94153175 0.24841172 0.17167149 0.95913776
 0.38445174 0.84870663 0.79648135 0.88550468 0.76404377 0.32697497
 0.01572988 0.2234747  0.27057126 0.60152494 0.05497489 0.87194838
 0.37186203 0.2458387  0.92835822 0.63873422 0.07717602 0.97052983
 0.36672949 0.73983238 0.60420775 0.89908386 0.12096925 0.60265232]


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [102]:
cuadrado = np.zeros((10, 10), dtype=int)

# primera fila
cuadrado[0, :] = 1
# última fila
cuadrado[-1, :] = 1
# primera columna
cuadrado[:, 0] = 1
# última columna
cuadrado[:, -1] = 1
print(cuadrado)


[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [104]:
matriz_16 = np.zeros((8, 8), dtype=int)

# ponemos a 1 los 0's alternando en cada columna / fila
matriz_16[::2, 1::2] = 1 # las filas impares
matriz_16[1::2, ::2] = 1 # las filas pares


print(matriz_16)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [117]:
# creamos el patrón a repetir
matriz_17 = np.array([['0','1'],
                   ['1', '0']])
matriz_17 = np.tile(matriz_17, (4,4))
print(matriz_17)

print("\n----------\n")
# creamos el patrón a repetir
matriz_17 = np.array([['◤','◥'],
                   ['◣', '◢']])
matriz_17 = np.tile(matriz_17, (4,4))
print(matriz_17)

[['0' '1' '0' '1' '0' '1' '0' '1']
 ['1' '0' '1' '0' '1' '0' '1' '0']
 ['0' '1' '0' '1' '0' '1' '0' '1']
 ['1' '0' '1' '0' '1' '0' '1' '0']
 ['0' '1' '0' '1' '0' '1' '0' '1']
 ['1' '0' '1' '0' '1' '0' '1' '0']
 ['0' '1' '0' '1' '0' '1' '0' '1']
 ['1' '0' '1' '0' '1' '0' '1' '0']]

----------

[['◤' '◥' '◤' '◥' '◤' '◥' '◤' '◥']
 ['◣' '◢' '◣' '◢' '◣' '◢' '◣' '◢']
 ['◤' '◥' '◤' '◥' '◤' '◥' '◤' '◥']
 ['◣' '◢' '◣' '◢' '◣' '◢' '◣' '◢']
 ['◤' '◥' '◤' '◥' '◤' '◥' '◤' '◥']
 ['◣' '◢' '◣' '◢' '◣' '◢' '◣' '◢']
 ['◤' '◥' '◤' '◥' '◤' '◥' '◤' '◥']
 ['◣' '◢' '◣' '◢' '◣' '◢' '◣' '◢']]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [89]:
# Crear matriz aleatoria 5x5
matriz = np.random.rand(5, 5)
print("Matriz original:\n", matriz)

# Calcular media y desviación estándar
media = np.mean(matriz)
estandar = np.std(matriz)

# Normalizar
matriz_normalizada = (matriz - media) / estandar
print("\nMatriz normalizada:\n", matriz_normalizada)


Matriz original:
 [[0.98578598 0.69767626 0.98667558 0.41480538 0.53241181]
 [0.13664493 0.56155452 0.43550103 0.68267965 0.02348519]
 [0.98633784 0.54895021 0.57622906 0.99744342 0.77120551]
 [0.5035747  0.65086404 0.30436797 0.38882144 0.59320929]
 [0.32302778 0.0372207  0.67469001 0.81118412 0.16181825]]

Matriz normalizada:
 [[ 1.53966817  0.5183623   1.54282167 -0.48437262 -0.06747544]
 [-1.47040981  0.03583112 -0.41100965  0.46520156 -1.87154415]
 [ 1.54162441 -0.00884929  0.08785015  1.58099203  0.77901249]
 [-0.16969866  0.35241999 -0.87585672 -0.57648181  0.14804253]
 [-0.8097105  -1.8228538   0.4368795   0.92073068 -1.38117415]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [131]:
#1. Crea una secuencia de números que vayan del 0 al 10.
x = np.arange(11)
print("Array inicial:", x)

# 2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1,
# todos los elementos cuyo valor se encuentre entre el 3 y el 8.
y = x.copy()
y[(y >= 3) & (y <= 8)] = -1
print(y)

# 3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8
z = x.copy()
z[(z >= 3) & (z <= 8)] = x[(x >= 3) & (x <= 8)]* -1
z[(z >= 3) & (z <= 8)] *= -1
print(z)

Array inicial: [ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]
